# /etc/supervisor/conf.d/secadordecafe-worker.conf
# Após copiar:
#   supervisorctl reread
#   supervisorctl update
#   supervisorctl status

[program:secadordecafe-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/secadordecafe/current/artisan queue:work redis --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/secadordecafe/worker-default.log
stopwaitsecs=3600

[program:secadordecafe-emails]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/secadordecafe/current/artisan queue:work redis --queue=emails --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/secadordecafe/worker-emails.log
stopwaitsecs=3600
